### ISSUE TITLE
'Username does not exist' on some accounts

### ISSUE THREAD

**Issue by rEnr3n** [Snbig/InstaTrack#11]
```
$ python --version
Python 3.8.1
$ python InstaTracker.py -u g.mi
[-] Username does not exist
$ python InstaTracker.py -u 'g.mi'
[-] Username does not exist
$ python InstaTracker.py -u so_____y_
[-] Username does not exist
$ python InstaTracker.py -u 'so_____y_'
[-] Username does not exist
$ python InstaTracker.py -u _glam.diva_
[-] Username does not exist
$ python InstaTracker.py -u '_glam.diva_'
[-] Username does not exist
```

**Comment by darylkell** [comment]
usernameToUserId() is returning JSON from Instagram that doesn't match the username being sought, so you're getting the 'does not exist' result being returned.  
Instagram could be returning the wrong result because the profiles that are being returned have paid to make themselves the highest priority result...?

A fix for Instatrack might be that the results being returned are iterated through until the right username is found, such as in the sample code below.

`import requests
names = ["g.mi", "so_____y_", "_glam.diva_"]

for name in names:
	data = requests.get(f"https://www.instagram.com/web/search/topsearch/?query={name}").json()

	for user_data in data["users"]:
		if user_data["user"]["username"] == name:
			print(f"Name: {name}\nID: {user_data['user']['pk']}\n")`

**Comment by Snbig** [comment]
Thank you for your notice. I'm too busy to fix the issue. would you please send me pull request?

**Comment by Snbig** [comment]
Fixed by new commit: https://github.com/Snbig/InstaTrack/commit/7946c6c7882b66410a83c62a2ddf3ba00b8f783e
 @darylkell, Thank you for your editing suggestion.
